name: 'Better Discord Notification'
author: 'Retr0-01'
description: 'A GitHub action for sending a better Discord notification embed, which can also be customized.'
inputs:
  webhook-url:
    description: 'The Discord webhook URL this notification will be send to.'
    required: true
  embed-color:
    description: "The embed's color."
    require: true
    default: '0'
  footer-icon:
    description: 'A small icon to put on the footer. Required in order to show the commit message count.'
    required: true
    default: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
runs:
  using: "composite"
  steps:
    - name: Get Current Time
      uses: josStorer/get-current-time@v2
      id: get_time
    - name: Get User Avatar
      uses: fjogeleit/http-request-action@master
      id: get_avatar
      with:
        url: "https://api.github.com/users/${{ github.actor }}"
        method: "GET"
    - name: Get Commits Messages
      # What we do here:
      #   - Remove any newlines
      #   - Replace double quotes with escaped double quotes
      #   - If the commit message are too big, cut them down.
      #   - Get how many commits we have through their unique commit ID. 
      id: get_commits
      run: |
        COMMIT_MESSAGES="${{ join(github.event.commits.*.message, '\n') }}" | sed -E ':a;N;$!ba;s/\r{0,1}\n/\\n/g'

        if [ -n $COMMIT_MESSAGES ] && [ ${#COMMIT_MESSAGES} -gt 1900 ]; then
          COMMIT_MESSAGES="$(echo "$COMMIT_MESSAGES" | cut -c 1-1900)"
          COMMIT_MESSAGES+="..."
        fi

        COMMIT_IDS="${{ join(github.event.commits.*.id, ', ') }}"
        IFS=', ' read -r -a COMMITS_ARRAY <<< "$COMMIT_IDS"
        COMMITS_COUNT="${#COMMITS_ARRAY[@]}"

        echo "::set-output name=COMMIT_MESSAGE::${COMMIT_MESSAGES}"
        echo "::set-output name=COMMIT_COUNT::$COMMITS_COUNT"
      shell: bash
    - name: Send Notification
      uses: fjogeleit/http-request-action@master
      with:
        url: ${{ inputs.webhook-url }}
        method: 'POST'
        data: '{"content":null,"embeds":[{"title":"${{github.repository}} [${{github.ref_name}}]","description":"${{steps.get_commits.outputs.COMMIT_MESSAGES}}","url":"${{github.event.compare}}","color":${{inputs.embed-color}},"footer":{"text":"${{steps.get_commits.outputs.COMMIT_COUNT}} new commit(s)","icon_url":"${{inputs.footer-icon}}"},"timestamp":"${{steps.get_time.outputs.time}}"}],"username":"${{github.actor}}","avatar_url":"${{fromJson(steps.get_avatar.outputs.response).avatar_url}}"}'
branding:
  icon: 'bell'
  color: 'blue'
